[6-2] pretty result

diff --git a/2018/hw6/ex2/check b/2018/hw6/ex2/check
--- a/2018/hw6/ex2/check
+++ b/2018/hw6/ex2/check
@@ -1,61 +1,55 @@
 #!/bin/bash
 
-TESTCASES=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26)
+R=$(tput setaf 1)
+G=$(tput setaf 2)
+Y=$(tput setaf 3)
+N=$(tput sgr0)
+BOLD=$(tput bold)
+
+WRONG="${R}✗ Wrong$N"
+CORRECT="${G}✓ Correct$N"
+WARNING="${Y}⚠$N"
+
 TESTDIR="examples"
-WRONG="$(tput setaf 1)✗$(tput sgr0)"
-CORRECT="$(tput setaf 2)✓$(tput sgr0)"
-WARNING="$(tput setaf 3)⚠$(tput sgr0)"
 
+set -e
 
-function result {
-    if [ 0 -lt "$1"  ]
-    then
-        echo "${WRONG}"
-    else
-        echo "${CORRECT}"
-    fi
-}
+echo "-- Compile sources --"
+make
+echo ""
 
-echo '# Compiling...'
-if ! make
-then
-    echo ''
-    echo 'Compile fail.'
-    exit 1
-fi
-echo ''
-
-echo "# Testing CPS-convert (${WARNING} Alpha ver. )"
-
-for TC in "${TESTCASES[@]}"
+echo "-- Testing CPS-convert (${WARNING} Alpha ver. ) --"
+for FULLNAME in $(find "$TESTDIR"/*.m | sort -V)
 do
-    TFILE="${TESTDIR}/test${TC}"
-    printf "Test %s..." "${TC}"
+    TEST="$(basename -- "$FULLNAME" .m)"
+    FILE="$TESTDIR/$TEST"
 
-    COMMCPS="./run -checkcps ${TFILE}.m"
-    COMMVAL="./run -checkval ${TFILE}.m"
+    printf "${BOLD}Testcase: %s$N " "$TEST"
+
+    COMMCPS="./run -checkcps $FILE.m"
+    COMMVAL="./run -checkval $FILE.m"
 
     FAIL=0
 
-    if ! eval "${COMMCPS}"
+    if ! eval "$COMMCPS"
     then
         FAIL=1
         FAILMSG="Wrong CPS-converted expression"
     fi
 
-    if ! eval "${COMMVAL}"
+    if ! eval "$COMMVAL"
     then
         FAIL=1
         FAILMSG="Wrong result value"
     fi
 
-    if [ 1 -eq ${FAIL} ]
+    if [ 1 -eq $FAIL ]
     then
-        echo "${WRONG} : ${FAILMSG}"
-        eval "./run -pp ${TFILE}.m"
-        echo '----------------------------------------'
+        echo "$WRONG : $FAILMSG"
+        eval "./run -pp $FILE.m"
+        echo ""
     else
-        echo "${CORRECT}"
+        echo "$CORRECT"
     fi
 done
-echo "(${WARNING} Alpha ver. CPS expression check is not reliable. )"
+echo "($WARNING Alpha ver. CPS expression check is not reliable. )"
